apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: django-k8s
spec:
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80