apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-k8s-web-deployment
  namespace: django-k8s
  labels:
    app: django-k8s-web-deployment
spec:
  selector:
    matchLabels:
      app: django-k8s-web-deployment
  template:
    metadata:
      labels:
        app: django-k8s-web-deployment
    spec:
      containers:
        - name: django-k8s-web
          image: django-k8s:v1
          envFrom:
            - secretRef:
                name: django-k8s-web-prod-env
          env:
            - name: PORT
              value: "8001"
          ports:
            - containerPort: 8001

---

apiVersion: v1
kind: Service
metadata:
  name: django-k8s-web-service
  namespace: django-k8s
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: django-k8s-web-deployment